export const SAMPLE_APPOINTMENTS = [
  {
    id: 'APT-2025-001',
    name: 'Peter Kuman',
    org: 'National Research Institute',
    purpose: 'Discuss the National Innovation Strategy and digital transformation roadmap for PNG',
    date: '2025-07-14',
    time: '10:00',
    type: 'Policy Meeting',
    phone: '+675 323 4567',
    email: 'p.kuman@nri.org.pg',
    delegates: 3,
    status: 'pending',
    submitted: '2025-06-20',
  },
  {
    id: 'APT-2025-002',
    name: 'Margaret Tokam',
    org: 'PNG Women in Business Council',
    purpose: 'Present findings from the Women Entrepreneurship Survey and request policy support',
    date: '2025-07-15',
    time: '14:00',
    type: 'Delegation Meeting',
    phone: '+675 311 2233',
    email: 'm.tokam@pngwib.org.pg',
    delegates: 5,
    status: 'approved',
    submitted: '2025-06-18',
  },
  {
    id: 'APT-2025-003',
    name: 'Fr. John Kaupa',
    org: 'Catholic Bishops Conference of PNG',
    purpose: 'Consultation on the Education Reform Bill and church-run schools policy implications',
    date: '2025-07-16',
    time: '09:00',
    type: 'Consultation',
    phone: '+675 325 7890',
    email: 'j.kaupa@catholicpng.org',
    delegates: 2,
    status: 'pending',
    submitted: '2025-06-22',
  },
  {
    id: 'APT-2025-004',
    name: 'Lina Warun',
    org: 'PNG Chamber of Commerce & Industry',
    purpose: 'Industry roundtable on SME tax incentives, export promotion and market access',
    date: '2025-07-10',
    time: '11:00',
    type: 'Business Meeting',
    phone: '+675 320 5566',
    email: 'l.warun@pngcoc.org.pg',
    delegates: 4,
    status: 'rejected',
    submitted: '2025-06-15',
  },
  {
    id: 'APT-2025-005',
    name: 'David Namah',
    org: 'Autonomous Bougainville Government',
    purpose: 'Update on autonomy referendum implementation and resource revenue sharing agreement',
    date: '2025-07-17',
    time: '13:00',
    type: 'Government Meeting',
    phone: '+675 319 1122',
    email: 'd.namah@abg.gov.pg',
    delegates: 6,
    status: 'pending',
    submitted: '2025-06-24',
  },
]

export const APPOINTMENT_TYPES = [
  'Policy Meeting',
  'Business Meeting',
  'Delegation Meeting',
  'Government Meeting',
  'Consultation',
  'Community Petition',
  'Media Interview',
  'Other',
]
